/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsConfigurationRouteImport } from './routes/settings.configuration'
import { Route as SettingsAvailableModelsRouteImport } from './routes/settings.available-models'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConfigurationRoute = SettingsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAvailableModelsRoute = SettingsAvailableModelsRouteImport.update({
  id: '/available-models',
  path: '/available-models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/available-models': typeof SettingsAvailableModelsRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/available-models': typeof SettingsAvailableModelsRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/available-models': typeof SettingsAvailableModelsRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/appearance'
    | '/settings/available-models'
    | '/settings/configuration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/appearance'
    | '/settings/available-models'
    | '/settings/configuration'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/appearance'
    | '/settings/available-models'
    | '/settings/configuration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/configuration': {
      id: '/settings/configuration'
      path: '/configuration'
      fullPath: '/settings/configuration'
      preLoaderRoute: typeof SettingsConfigurationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/available-models': {
      id: '/settings/available-models'
      path: '/available-models'
      fullPath: '/settings/available-models'
      preLoaderRoute: typeof SettingsAvailableModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAvailableModelsRoute: typeof SettingsAvailableModelsRoute
  SettingsConfigurationRoute: typeof SettingsConfigurationRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAvailableModelsRoute: SettingsAvailableModelsRoute,
  SettingsConfigurationRoute: SettingsConfigurationRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
