/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsageAndLimitsRouteImport } from './routes/settings.usage-and-limits'
import { Route as SettingsToolsRouteImport } from './routes/settings.tools'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsPermissionsRouteImport } from './routes/settings.permissions'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsHealthRouteImport } from './routes/settings.health'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsageAndLimitsRoute = SettingsUsageAndLimitsRouteImport.update({
  id: '/usage-and-limits',
  path: '/usage-and-limits',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsToolsRoute = SettingsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHealthRoute = SettingsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/health': typeof SettingsHealthRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/settings/usage-and-limits': typeof SettingsUsageAndLimitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/health': typeof SettingsHealthRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/settings/usage-and-limits': typeof SettingsUsageAndLimitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/health': typeof SettingsHealthRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/settings/usage-and-limits': typeof SettingsUsageAndLimitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/advanced'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/health'
    | '/settings/models'
    | '/settings/permissions'
    | '/settings/providers'
    | '/settings/tools'
    | '/settings/usage-and-limits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/advanced'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/health'
    | '/settings/models'
    | '/settings/permissions'
    | '/settings/providers'
    | '/settings/tools'
    | '/settings/usage-and-limits'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/advanced'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/health'
    | '/settings/models'
    | '/settings/permissions'
    | '/settings/providers'
    | '/settings/tools'
    | '/settings/usage-and-limits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/usage-and-limits': {
      id: '/settings/usage-and-limits'
      path: '/usage-and-limits'
      fullPath: '/settings/usage-and-limits'
      preLoaderRoute: typeof SettingsUsageAndLimitsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools': {
      id: '/settings/tools'
      path: '/tools'
      fullPath: '/settings/tools'
      preLoaderRoute: typeof SettingsToolsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/health': {
      id: '/settings/health'
      path: '/health'
      fullPath: '/settings/health'
      preLoaderRoute: typeof SettingsHealthRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHealthRoute: typeof SettingsHealthRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsToolsRoute: typeof SettingsToolsRoute
  SettingsUsageAndLimitsRoute: typeof SettingsUsageAndLimitsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHealthRoute: SettingsHealthRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsToolsRoute: SettingsToolsRoute,
  SettingsUsageAndLimitsRoute: SettingsUsageAndLimitsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
