// init-templates.ts -- pure functions that generate YAML strings for kiln init
// No I/O -- all inputs are passed as parameters

export interface InitOptions {
  readonly appName: string;
  readonly domain: string;
  readonly domainDisplayName: string;
  readonly provider: string;
  readonly channels: readonly string[];
  readonly teamMode: string;
  readonly qualityGates: readonly { name: string; command: string; description: string }[];
}

interface ProviderDefaults {
  readonly model: string;
  readonly apiKeyEnv: string;
}

const PROVIDER_DEFAULTS: Record<string, ProviderDefaults> = {
  anthropic: { model: "claude-sonnet-4-6", apiKeyEnv: "ANTHROPIC_API_KEY" },
  openai: { model: "gpt-4o", apiKeyEnv: "OPENAI_API_KEY" },
  deepseek: { model: "deepseek-chat", apiKeyEnv: "DEEPSEEK_API_KEY" },
  ollama: { model: "llama3.2", apiKeyEnv: "" },
  lmstudio: { model: "qwen/qwen3.5-9b", apiKeyEnv: "" },
};

/** Generate app.yaml content for the initialized project */
export function generateAppYaml(options: InitOptions): string {
  const { appName, channels, qualityGates } = options;
  const channelsLine = channels.join(", ");

  const qualityGatesSection =
    qualityGates.length > 0
      ? qualityGates
          .map((g) => `      - name: ${g.name}\n        command: "${g.command}"\n        description: ${g.description}`)
          .join("\n")
      : "      []";

  return `# App configuration for ${appName}
# Generated by kiln init

name: ${appName}
channels: [${channelsLine}]

memory:
  scopes: [user, "agent:planner", "agent:worker", "project:default"]
  backend: sqlite+fts5
  sync: git

router:
  rules: []
  fallback: main

teams:
  main:
    agents:
      planner:
        name: Planner
        role: Planning Specialist
        goal: Plan and design solutions with minimal complexity
        tier: reasoning
        tools: []
        structured: true
      worker:
        name: Worker
        role: Implementation Specialist
        goal: Implement clean, well-tested code following conventions
        tier: coding
        tools:
          - resource_list
          - resource_template_list
          - resource_read
          - kiln_cost_track
        count: 2
        sandbox: true

    workflow:
      phases: [analyze, research, architect, implement, verify, synthesize]
      gates:
        architect:
          requires: [human_approval]
        verify:
          requires: [tests_pass]
      maxIterations: 3

    capabilities:
      - name: kiln_init
        description: Initialize a session with task and context
        tags: [session]
      - name: kiln_phase_start
        description: Start a new phase in the workflow
        tags: [orchestrator]
      - name: resource_list
        description: List shared Kiln resources available to the current session
        tags: [resources]
      - name: resource_template_list
        description: List shared Kiln resource templates, including Memory Lattice templates
        tags: [resources, memory]
      - name: resource_read
        description: Read a bounded kiln:// resource URI such as kiln://memory/graph
        tags: [resources, memory]
      - name: kiln_cost_track
        description: Track token usage and cost for an agent interaction
        tags: [cost]
      - name: kiln_cost_summary
        description: Get cost breakdown by role and total
        tags: [cost]

    qualityGates:
${qualityGatesSection}
`;
}

/** Generate gateway.yaml content for the initialized project */
export function generateGatewayYaml(options: InitOptions): string {
  const { appName, provider } = options;
  const defaults = PROVIDER_DEFAULTS[provider] ?? PROVIDER_DEFAULTS["anthropic"]!;

  const apiKeyLine =
    defaults.apiKeyEnv !== ""
      ? `        apiKeyEnv: ${defaults.apiKeyEnv}`
      : `        # no API key required for local models`;

  return `# Gateway configuration
# Generated by kiln init

port: 4800

apps:
  - name: ${appName}
    path: ./app.yaml
    channels:
      - type: api
        path: /api/${appName}
    modeB:
      runtime: provider-adapter
      provider:
        name: ${provider}
        model: ${defaults.model}
${apiKeyLine}
`;
}
