/**
 * Kiln Wrapper -- orchestrates the lifecycle around Claude Code sessions.
 * Pre-session: detect stack, load memory, build system prompt, configure MCP.
 * During: Claude Code runs with Kiln MCP tools available.
 * Post-session: save memory, generate report, sync to git.
 */

import type { DomainConfig } from "@kilnai/core";
import type { KilnPermissionPolicy } from "./session.js";

/** Session mode determines how Claude Code is launched */
export type SessionMode =
  | "api-key"       // Uses Anthropic API key directly (default)
  | "byok";         // Bring your own key (any provider)

/** Pre-session context built by the wrapper */
export interface SessionContext {
  readonly mode: SessionMode;
  readonly domain: DomainConfig;
  readonly systemPrompt: string;
  readonly mcpServerEntryPath: string;
  readonly workingDirectory: string;
  readonly task: string;
}

/** Post-session report generated by the wrapper */
export interface SessionReport {
  readonly sessionId: string;
  readonly task: string;
  readonly domain: string;
  readonly phaseReached: string;
  readonly cost: {
    readonly total: number;
    readonly byRoleModel: Record<string, number>;
  };
  readonly duration: number;
}

/** Wrapper configuration */
export interface WrapperConfig {
  readonly mode: SessionMode;
  readonly apiKey?: string;
  readonly provider?: string;
  readonly permissionPolicy: KilnPermissionPolicy;
}

export { ClaudeSession } from "./claude-code-process.js";
export type { ClaudeSessionConfig } from "./claude-code-process.js";
export { OpenCodeSession } from "./opencode-session.js";
export type { OpenCodeSessionConfig } from "./opencode-session.js";
export { CodexSession } from "./codex-session.js";
export type { CodexSessionConfig } from "./codex-session.js";
export { SessionManager } from "./session-manager.js";
export type { KilnAppConfig, SystemPromptOptions } from "../config.js";
export type {
  CostTrackingMode,
  SessionEvent,
  SessionCapabilities,
  SessionRunOptions,
  IKilnSession,
  ApprovalMode,
  SandboxMode,
  KilnPermissionPolicy,
} from "./session.js";
export {
  SessionRegistry,
  createDefaultRegistry,
  SessionUnavailableError,
  translatePermission,
} from "./session-registry.js";
export type {
  ProviderId,
  SessionRequirements,
  SessionProviderDescriptor,
  ProviderCreateConfig,
  SelectionResult,
  CandidateScore,
  ClaudeBackendConfig,
  CodexBackendConfig,
  OpenCodeBackendConfig,
  BackendConfig,
} from "./session-registry.js";
