/**
 * Kiln Wrapper -- orchestrates the lifecycle around Claude Code sessions.
 * Pre-session: detect stack, load memory, build system prompt, configure MCP.
 * During: Claude Code runs with Kiln MCP tools available.
 * Post-session: save memory, generate report, sync to git.
 */

import type { DomainConfig } from "@kilnai/core";
import type { ProjectedContext, ProjectedContextBlockKind } from "../application/context-types.js";
import type { KilnPermissionPolicy } from "./session.js";

/** Session mode determines how Claude Code is launched */
export type SessionMode =
  | "api-key"       // Uses Anthropic API key directly (default)
  | "byok"          // Bring your own key (any provider)
  | "cli-wrapper";  // Use an installed CLI session wrapper without API keys

export type ResumeStrategy = "none" | "cache-first" | "provider-native" | "fallback-replay";

export interface ResumeFeedback {
  readonly sampleSize: number;
  readonly preferredStrategy?: Extract<ResumeStrategy, "cache-first" | "provider-native" | "fallback-replay">;
  readonly influencedChoice: boolean;
}

export interface ResumeOutcome {
  readonly succeeded: boolean;
  readonly finalProvider?: string;
  readonly costUsd: number;
  readonly toolCallCount: number;
  readonly durationMs: number;
  readonly verificationPassed?: boolean;
}

export interface ContextGovernanceSummary {
  readonly selectedTokens: number;
  readonly tokenBudget?: number;
  readonly overflow: boolean;
  readonly selectedCount: number;
  readonly deferredCount: number;
  readonly selectedKinds: Partial<Record<ProjectedContextBlockKind, number>>;
  readonly deferredKinds: Partial<Record<ProjectedContextBlockKind, number>>;
  readonly selectedSources: Record<string, number>;
  readonly deferredSources: Record<string, number>;
  readonly deferredReasons: readonly string[];
}

/** Pre-session context built by the wrapper */
export interface SessionContext {
  readonly mode: SessionMode;
  readonly domain: DomainConfig;
  readonly systemPrompt: string;
  readonly projectedContext: ProjectedContext;
  readonly mcpServerEntryPath: string;
  readonly workingDirectory: string;
  readonly task: string;
  readonly worktreePath?: string;
  readonly isWorker?: boolean;
  readonly continuationSessionId?: string;
  readonly resumeStrategy: ResumeStrategy;
  readonly resumeFeedback?: ResumeFeedback;
}

/** Post-session report generated by the wrapper */
export interface SessionReport {
  readonly sessionId: string;
  readonly task: string;
  readonly domain: string;
  readonly phaseReached: string;
  readonly cost: {
    readonly total: number;
    readonly byRoleModel: Record<string, number>;
    readonly breakdown?: Array<{
      readonly turn: number;
      readonly inputTokens: number;
      readonly outputTokens: number;
      readonly cacheReadTokens: number;
      readonly costUsd: number;
    }>;
  };
  readonly duration: number;
  readonly verificationResult?: {
    readonly passed: boolean;
    readonly checks: readonly {
      readonly name: string;
      readonly passed: boolean;
      readonly output: string;
      readonly duration: number;
    }[];
  };
  readonly evalScore?: {
    readonly score: number;
    readonly label: "excellent" | "good" | "fair" | "poor";
    readonly signals: readonly string[];
  };
  readonly resumedFrom?: string;
  readonly resumeStrategy?: ResumeStrategy;
  readonly resumeFeedback?: ResumeFeedback;
  readonly resumeOutcome?: ResumeOutcome;
  readonly contextGovernance?: ContextGovernanceSummary;
}

/** Wrapper configuration */
export interface WrapperConfig {
  readonly mode: SessionMode;
  readonly apiKey?: string;
  readonly provider?: string;
  readonly permissionPolicy: KilnPermissionPolicy;
}

export { buildPreamble } from "./preamble-builder.js";
export type {
  ProjectedContext,
  ProjectedContextBlock,
  ProjectedContextBlockKind,
} from "../application/context-types.js";
export type { SessionLedger } from "../application/session-ledger.js";
export { WorktreeManager } from "./worktree-manager.js";
export { ClaudeSession } from "./claude-code-process.js";
export type { ClaudeSessionConfig } from "./claude-code-process.js";
export { OpenCodeSession } from "./opencode-session.js";
export { CodexSession } from "./codex-session.js";
export { SessionManager } from "./session-manager.js";
export type { KilnAppConfig, SystemPromptOptions } from "../config.js";
export type {
  CostTrackingMode,
  SessionEvent,
  SessionCapabilities,
  SessionRunOptions,
  IKilnSession,
  KilnPermissionAction,
  KilnPermissionApproval,
  KilnSandboxMode,
  KilnToolPermissionRule,
  KilnCommandPermissionRule,
  KilnFileGovernancePolicy,
  KilnDataDestination,
  KilnDataFirewallRule,
  KilnAgentPermissionScope,
  KilnPermissionPolicy,
} from "./session.js";
export {
  SessionRegistry,
  createDefaultRegistry,
  getProviderDisplayInfo,
  translatePermission,
} from "./session-registry.js";
export type {
  ProviderId,
  ProviderDisplayInfo,
  SessionRequirements,
} from "./session-registry.js";

export { SessionStore } from "./session-store.js";
export type { SessionRecord } from "./session-store.js";
export { ApprovalMemoryStore } from "./approval-memory-store.js";
export type {
  ApprovalScope,
  ApprovalSurface,
  ApprovalMemoryRecord,
  ApprovalGrantInput,
  ApprovalMatchQuery,
} from "./approval-memory-store.js";
export { createPermissionEvaluator, resolveEffectivePermissionPolicy } from "./permission-evaluator.js";
export type {
  PermissionEvaluator,
  PermissionEvaluationRequest,
  PermissionDecision,
  PermissionDecisionSource,
  PermissionDecisionMatch,
  PermissionScopeInfo,
  EffectivePermissionPolicyResult,
} from "./permission-evaluator.js";

export { HookRegistry } from "./hook-registry.js";
export { HookExecutor } from "./hook-executor.js";
export type { HookContext, HookResult } from "./hook-executor.js";
export type {
  HookEvent,
  HookHandler,
  HookRule,
  KilnHooksConfig,
} from "../kiln-yaml-types.js";
