/**
 * Kiln Wrapper -- orchestrates the lifecycle around Claude Code sessions.
 * Pre-session: detect stack, load memory, build system prompt, configure MCP.
 * During: Claude Code runs with Kiln MCP tools available.
 * Post-session: save memory, generate report, sync to git.
 */

import type { DomainConfig } from "@kilnai/core";

/** Session mode determines how Claude Code is launched */
export type SessionMode =
  | "api-key"       // Uses Anthropic API key directly (default)
  | "byok";         // Bring your own key (any provider)

/** Pre-session context built by the wrapper */
export interface SessionContext {
  readonly mode: SessionMode;
  readonly domain: DomainConfig;
  readonly systemPrompt: string;
  readonly mcpServerEntryPath: string;
  readonly memorySnapshot: string;
  readonly workingDirectory: string;
  readonly task: string;
}

/** Post-session report generated by the wrapper */
export interface SessionReport {
  readonly sessionId: string;
  readonly task: string;
  readonly domain: string;
  readonly phaseReached: string;
  readonly phasesCompleted: number;
  readonly totalPhases: number;
  readonly tasksCompleted: number;
  readonly tasksPruned: number;
  readonly filesModified: number;
  readonly cost: {
    readonly total: number;
    readonly byRole: Record<string, number>;
  };
  readonly memory: {
    readonly recalled: number;
    readonly saved: number;
  };
  readonly qualityGates: {
    readonly passed: number;
    readonly failed: number;
    readonly violations: readonly string[];
  };
  readonly duration: number;
}

/** Wrapper configuration */
export interface WrapperConfig {
  readonly mode: SessionMode;
  readonly apiKey?: string;
  readonly provider?: string;
  readonly claudeCodePath: string;
  readonly dangerouslySkipPermissions: boolean;
  readonly sandbox: boolean;
  readonly autoApprove: boolean;
  readonly autoApproveTimeout: number;
}

export { ClaudeSession } from "./claude-code-process.js";
export type { ClaudeSessionConfig } from "./claude-code-process.js";
export { buildSystemPrompt, buildMcpConfig } from "./context-builder.js";
export { SessionManager } from "./session-manager.js";
export type { KilnAppConfig, SystemPromptOptions } from "../config.js";
