import type { CSSProperties } from "react";

const codeForeground = "var(--color-code-foreground)";
const codeBackground = "var(--color-code-background)";

/** GUI-owned Highlight.js scope mapping over the canonical operator palette. */
export const OPERATOR_CODE_SYNTAX_STYLE: Readonly<Record<string, CSSProperties>> = {
  hljs: {
    display: "block",
    overflowX: "auto",
    padding: "0.5em",
    color: codeForeground,
    background: codeBackground,
  },
  "hljs-comment": { color: "var(--color-text-muted)", fontStyle: "italic" },
  "hljs-quote": { color: "var(--color-text-muted)", fontStyle: "italic" },
  "hljs-doctag": { color: "var(--color-kiln-accent)" },
  "hljs-keyword": { color: "var(--color-kiln-accent)" },
  "hljs-formula": { color: "var(--color-kiln-accent)" },
  "hljs-section": { color: "var(--color-error)" },
  "hljs-name": { color: "var(--color-error)" },
  "hljs-selector-tag": { color: "var(--color-error)" },
  "hljs-deletion": { color: "var(--color-error)" },
  "hljs-subst": { color: codeForeground },
  "hljs-literal": { color: "var(--color-info)" },
  "hljs-string": { color: "var(--color-success)" },
  "hljs-regexp": { color: "var(--color-success)" },
  "hljs-addition": { color: "var(--color-success)" },
  "hljs-attribute": { color: "var(--color-success)" },
  "hljs-meta-string": { color: "var(--color-success)" },
  "hljs-built_in": { color: "var(--color-update)" },
  "hljs-class .hljs-title": { color: "var(--color-update)" },
  "hljs-attr": { color: "var(--color-info)" },
  "hljs-variable": { color: codeForeground },
  "hljs-template-variable": { color: codeForeground },
  "hljs-type": { color: "var(--color-update)" },
  "hljs-selector-class": { color: "var(--color-info)" },
  "hljs-selector-attr": { color: "var(--color-info)" },
  "hljs-selector-pseudo": { color: "var(--color-info)" },
  "hljs-number": { color: "var(--color-info)" },
  "hljs-symbol": { color: "var(--color-update)" },
  "hljs-bullet": { color: "var(--color-update)" },
  "hljs-link": { color: "var(--color-update)", textDecoration: "underline" },
  "hljs-meta": { color: "var(--color-update)" },
  "hljs-selector-id": { color: "var(--color-update)" },
  "hljs-title": { color: "var(--color-update)" },
  "hljs-emphasis": { fontStyle: "italic" },
  "hljs-strong": { fontWeight: "bold" },
};

/** Prism scope mapping for the workspace renderer using the same semantic roles. */
export const OPERATOR_WORKSPACE_CODE_SYNTAX_STYLE: Readonly<Record<string, CSSProperties>> = {
  'pre[class*="language-"]': {
    background: codeBackground,
    color: codeForeground,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "12px",
    lineHeight: "1.25rem",
    margin: 0,
    padding: "0.75rem 0",
    tabSize: 2,
  },
  'code[class*="language-"]': {
    background: "transparent",
    color: codeForeground,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    tabSize: 2,
  },
  comment: { color: "var(--color-text-muted)" },
  prolog: { color: "var(--color-text-muted)" },
  doctype: { color: "var(--color-text-muted)" },
  cdata: { color: "var(--color-text-muted)" },
  punctuation: { color: codeForeground },
  property: { color: "var(--color-update)" },
  tag: { color: "var(--color-error)" },
  boolean: { color: "var(--color-info)" },
  number: { color: "var(--color-info)" },
  constant: { color: "var(--color-info)" },
  symbol: { color: "var(--color-update)" },
  selector: { color: "var(--color-success)" },
  string: { color: "var(--color-success)" },
  char: { color: "var(--color-success)" },
  builtin: { color: "var(--color-update)" },
  inserted: { color: "var(--color-success)" },
  operator: { color: "var(--color-kiln-accent)" },
  entity: { color: "var(--color-kiln-accent)" },
  url: { color: "var(--color-update)" },
  variable: { color: codeForeground },
  atrule: { color: "var(--color-kiln-accent)" },
  attrvalue: { color: "var(--color-success)" },
  function: { color: "var(--color-update)" },
  className: { color: "var(--color-update)" },
  keyword: { color: "var(--color-kiln-accent)" },
  regex: { color: "var(--color-success)" },
  important: { color: "var(--color-kiln-accent)", fontWeight: 600 },
  deleted: { color: "var(--color-error)" },
};
