import { beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

vi.mock("node:fs", () => {
  return {
    readFileSync: vi.fn(),
    writeFileSync: vi.fn(),
  };
});

vi.mock("../../src/application/agent-loader.js", () => ({
  loadAgentDefinitions: vi.fn(),
}));

vi.mock("../../src/config/config-merger.js", () => ({
  loadKilnConfig: vi.fn(),
}));

vi.mock("../../src/application/instruction-profile-loader.js", () => ({
  loadInstructionProfiles: vi.fn(),
  findInstructionProfile: vi.fn((profiles, name) =>
    profiles.find((profile: { name: string }) => profile.name === name)),
}));

import { loadAgentDefinitions } from "../../src/application/agent-loader.js";
import { loadKilnConfig } from "../../src/config/config-merger.js";
import { loadInstructionProfiles } from "../../src/application/instruction-profile-loader.js";
import { writeAgentsMdProjection } from "../../src/application/agents-md-projection.js";

const PROJECT_PATH = "/workspace/project";
const TARGET_PATH = join(PROJECT_PATH, "AGENTS.md");

const readFileSyncMock = readFileSync as unknown as ReturnType<typeof vi.fn>;
const writeFileSyncMock = writeFileSync as unknown as ReturnType<typeof vi.fn>;
const loadAgentDefinitionsMock = loadAgentDefinitions as unknown as ReturnType<typeof vi.fn>;
const loadKilnConfigMock = loadKilnConfig as unknown as ReturnType<typeof vi.fn>;
const loadInstructionProfilesMock = loadInstructionProfiles as unknown as ReturnType<typeof vi.fn>;

function writtenContent(callIndex = 0): string {
  return String(writeFileSyncMock.mock.calls[callIndex]?.[1] ?? "");
}

describe("agents-md-projection", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    readFileSyncMock.mockReset();
    writeFileSyncMock.mockReset();
    loadAgentDefinitionsMock.mockReset();
    loadKilnConfigMock.mockReset();
    loadInstructionProfilesMock.mockReset();
    loadInstructionProfilesMock.mockReturnValue([]);
  });

  it("generates correct markdown with agents and kiln.yaml present", async () => {
    loadAgentDefinitionsMock.mockResolvedValue([
      {
        name: "Planner",
        displayName: "Hal",
        role: "Planning specialist",
        tools: ["read", "write"],
        model: "gpt-5.4",
        skills: ["sequel-spring"],
        instructionProfiles: ["sequel-engineering"],
        scope: "project",
      },
      {
        name: "Scout",
        role: "Mapper",
        scope: "global",
      },
    ]);
    loadKilnConfigMock.mockResolvedValue({
      version: "1",
      domain: "cinema",
      provider: "codex",
      model: { default: "gpt-5.4" },
      maxDepth: 6,
      parallelWorkers: 2,
      activeInstructionProfiles: ["sequel-engineering"],
    });
    loadInstructionProfilesMock.mockReturnValue([{
      name: "sequel-engineering",
      scope: "global",
      filePath: "/home/tester/.kiln/instructions/sequel-engineering.md",
    }]);

    const result = await writeAgentsMdProjection(PROJECT_PATH);
    const content = writtenContent();

    expect(result).toEqual({
      written: true,
      path: TARGET_PATH,
      errors: [],
    });
    expect(loadKilnConfigMock).toHaveBeenCalledWith(PROJECT_PATH);
    expect(content).toContain("# Agents");
    expect(content).toContain("> Generated by kiln sync --agents-md. Do not edit manually.");
    expect(content).toContain("## Team Configuration");
    expect(content).toContain("| Setting | Value |");
    expect(content).toContain("|---------|-------|");
    expect(content).toContain("## Agents");
    expect(content).toContain("| Name | Display | Role | Tools | Model | Skills | Instruction Profiles |");
    expect(content).toContain("|------|---------|------|-------|-------|--------|----------------------|");
    expect(content).toContain("## Active Instruction Profiles");
    expect(content).toContain("sequel-engineering (global): /home/tester/.kiln/instructions/sequel-engineering.md");
    expect(content).toContain("cinema");
    expect(content).toContain("codex");
    expect(content).toContain("gpt-5.4");
    expect(content).toContain("6");
    expect(content).toContain("2");
    expect(content).toContain("Planner (project)");
    expect(content).toContain("Hal");
    expect(content).toContain("Scout (global)");
    expect(content).toContain("read, write");
    expect(content).toContain("sequel-spring");
    expect(content).toContain("sequel-engineering");
  });

  it("generates file with no agents (empty state message)", async () => {
    loadAgentDefinitionsMock.mockResolvedValue([]);
    loadKilnConfigMock.mockResolvedValue({
      version: "1",
      domain: "default",
    });

    const result = await writeAgentsMdProjection(PROJECT_PATH);
    const content = writtenContent();

    expect(result.written).toBe(true);
    expect(content).toContain("No agent profiles defined. Create .kiln/agents/<name>.md to add one.");
    expect(content).toContain("| Name | Display | Role | Tools | Model | Skills | Instruction Profiles |");
    expect(content).toContain("|------|---------|------|-------|-------|--------|----------------------|");
  });

  it("generates file when kiln.yaml is null (no Team Configuration table)", async () => {
    loadAgentDefinitionsMock.mockResolvedValue([
      {
        name: "Reviewer",
        role: "Code review",
        scope: "global",
      },
    ]);
    loadKilnConfigMock.mockResolvedValue(null);

    const result = await writeAgentsMdProjection(PROJECT_PATH);
    const content = writtenContent();

    expect(result.written).toBe(true);
    expect(content).not.toContain("Team Configuration");
    expect(content).toContain("## Agents");
    expect(content).toContain("Reviewer (global)");
  });

  it("returns written:false and error message when writeFileSync throws", async () => {
    loadAgentDefinitionsMock.mockResolvedValue([]);
    loadKilnConfigMock.mockResolvedValue(null);
    writeFileSyncMock.mockImplementation(() => {
      throw new Error("disk full");
    });

    const result = await writeAgentsMdProjection(PROJECT_PATH);

    expect(result.written).toBe(false);
    expect(result.path).toBe(TARGET_PATH);
    expect(result.errors[0]).toContain("disk full");
  });

  it("is idempotent: calling twice with same data produces same output", async () => {
    loadAgentDefinitionsMock.mockResolvedValue([
      {
        name: "Architect",
        role: "System architect",
        tools: ["read"],
        model: "gpt-5.4",
        skills: ["sequel-spring", "refactor"],
        scope: "project",
      },
    ]);
    loadKilnConfigMock.mockResolvedValue({
      version: "1",
      domain: "cinema",
      provider: "claude",
      model: { default: "claude-sonnet-4-6" },
      maxDepth: 3,
      parallelWorkers: 1,
    });

    const firstResult = await writeAgentsMdProjection(PROJECT_PATH);
    const secondResult = await writeAgentsMdProjection(PROJECT_PATH);

    expect(firstResult.written).toBe(true);
    expect(secondResult.written).toBe(true);
    expect(writtenContent(0)).toBe(writtenContent(1));
  });
});
