import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadAgentDefinitions } from "../application/agent-loader.js";
import { findInstructionProfile, loadInstructionProfiles } from "./instruction-profile-loader.js";
import { loadKilnConfig } from "../config/config-merger.js";

export interface AgentsMdProjectionResult {
  written: boolean;
  path: string;
  errors: string[];
}

export async function writeAgentsMdProjection(projectPath: string): Promise<AgentsMdProjectionResult> {
  const targetPath = join(projectPath, "AGENTS.md");

  try {
    const agents = await loadAgentDefinitions(projectPath);
    const instructionProfiles = loadInstructionProfiles(projectPath);
    const kilnYaml = await loadKilnConfig(projectPath);

    const domain = kilnYaml?.domain ?? "default";
    const provider = kilnYaml?.provider ?? "claude";
    const model = kilnYaml?.model?.default ?? "provider default";
    const maxDepth = String(kilnYaml?.maxDepth ?? 3);
    const parallelWorkers = String(kilnYaml?.parallelWorkers ?? 1);

    const rows = [...agents]
      .sort((left, right) => left.name.localeCompare(right.name))
      .map((agent) => {
        const tools = agent.tools && agent.tools.length > 0 ? agent.tools.join(", ") : "-";
        const skills = agent.skills && agent.skills.length > 0 ? agent.skills.join(", ") : "-";
        const displayName = agent.displayName ?? "-";
        const instructionProfiles = agent.instructionProfiles && agent.instructionProfiles.length > 0
          ? agent.instructionProfiles.join(", ")
          : "-";
        return `| ${agent.name} (${agent.scope}) | ${displayName} | ${agent.role} | ${tools} | ${agent.model ?? "-"} | ${skills} | ${instructionProfiles} |`;
      });

    const lines: string[] = [
      "# Agents",
      "",
      "> Generated by kiln sync --agents-md. Do not edit manually.",
      "",
    ];

    if (kilnYaml) {
      lines.push(
        "## Team Configuration",
        "",
        "| Setting | Value |",
        "|---------|-------|",
        `| Domain | ${domain} |`,
        `| Default Provider | ${provider} |`,
        `| Default Model | ${model} |`,
        `| Max Depth | ${maxDepth} |`,
        `| Parallel Workers | ${parallelWorkers} |`,
        "",
      );
      if (kilnYaml.activeInstructionProfiles && kilnYaml.activeInstructionProfiles.length > 0) {
        const profileLines = kilnYaml.activeInstructionProfiles.map((profileId) => {
          const profile = findInstructionProfile(instructionProfiles, profileId);
          return profile
            ? `- ${profile.name} (${profile.scope}): ${profile.filePath}`
            : `- ${profileId} (missing; run kiln sync after creating the canonical profile)`;
        });
        lines.push(
          "## Active Instruction Profiles",
          "",
          "Read these canonical Kiln instruction profiles before work. They are the source of durable operator/team doctrine; this AGENTS.md section is only a projection.",
          "",
          ...profileLines,
          "",
        );
      }
    }

    lines.push(
      "## Agents",
      "",
      "| Name | Display | Role | Tools | Model | Skills | Instruction Profiles |",
      "|------|---------|------|-------|-------|--------|----------------------|",
      ...rows,
      "",
    );

    if (rows.length === 0) {
      lines.push("No agent profiles defined. Create .kiln/agents/<name>.md to add one.", "");
    }

    lines.push(
      "## Usage",
      "",
      "Use `kiln run --agent <name>` to select an agent profile.",
      "Agent definitions live in `.kiln/agents/*.md` (project) or `~/.kiln/agents/*.md` (global).",
      "",
    );

    writeFileSync(targetPath, `${lines.join("\n")}`, "utf-8");

    return { written: true, path: targetPath, errors: [] };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { written: false, path: targetPath, errors: [message] };
  }
}
