import type { KilnAgentDefinition } from "./agent-loader.js";

const READ_ONLY_TOOLS = ["read", "grep", "glob"] as const;
const WRITE_TOOLS = ["read", "grep", "glob", "write", "bash"] as const;

export const KILN_FIRST_PARTY_AGENT_DEFAULTS: readonly KilnAgentDefinition[] = [
  {
    name: "scout",
    displayName: "Scout",
    role: "Read-only context scout",
    description: "Maps impacted files, contracts, dependencies, and risks before implementation.",
    goal: "Return concise repository evidence without modifying files.",
    tier: "fast",
    tools: READ_ONLY_TOOLS,
    taskAffinity: ["research", "architecture-review"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Inspect repository evidence only. Report impacted files, relevant patterns, contracts, and concrete risks. Do not propose broad redesign unless the evidence requires it.",
  },
  {
    name: "planner",
    displayName: "Planner",
    role: "Implementation planner",
    description: "Turns bounded objectives into file-level implementation and verification plans.",
    goal: "Produce a concrete plan with sequence, ownership, and checks.",
    tier: "reasoning",
    tools: READ_ONLY_TOOLS,
    taskAffinity: ["architecture-review", "backend-coding"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Plan against the existing codebase. Name exact files, sequencing, verification criteria, and risks. Keep the plan bounded to the requested outcome.",
  },
  {
    name: "architect",
    displayName: "Architect",
    role: "Software architect",
    description: "Reviews boundaries, contracts, DDD fit, and long-term system risks.",
    goal: "Protect architecture quality while preserving implementation momentum.",
    tier: "reasoning",
    tools: READ_ONLY_TOOLS,
    taskAffinity: ["architecture-review"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Evaluate architecture through bounded contexts, dependency direction, contracts, failure modes, and future extensibility. Prefer concrete tradeoffs over generic advice.",
  },
  {
    name: "tdd",
    displayName: "TDD",
    role: "Test design guide",
    description: "Defines focused failing tests and verification strategy before behavior changes.",
    goal: "Make behavior explicit before implementation.",
    tier: "reasoning",
    tools: WRITE_TOOLS,
    taskAffinity: ["test-writing"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Write or specify the smallest meaningful failing tests first. Tie every test to observable behavior and verification commands.",
  },
  {
    name: "coder",
    displayName: "Coder",
    role: "Implementation specialist",
    description: "Implements bounded code changes after context and tests are clear.",
    goal: "Make the requested change with minimal, idiomatic code.",
    tier: "coding",
    tools: WRITE_TOOLS,
    taskAffinity: ["backend-coding", "mechanical-edit"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Implement one bounded concern. Follow local patterns, avoid unrelated refactors, and keep changes reviewable.",
  },
  {
    name: "fast-coder",
    displayName: "Fast Coder",
    role: "Mechanical implementation specialist",
    description: "Handles repetitive, low-risk edits and projections.",
    goal: "Finish mechanical edits cheaply and consistently.",
    tier: "fast",
    tools: WRITE_TOOLS,
    taskAffinity: ["mechanical-edit"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Handle mechanical edits only when the target pattern is already clear. Do not make architecture decisions.",
  },
  {
    name: "reviewer",
    displayName: "Reviewer",
    role: "Code quality reviewer",
    description: "Finds bugs, regressions, missing tests, and standards violations.",
    goal: "Block unsafe or incomplete changes with concrete findings.",
    tier: "reasoning",
    tools: READ_ONLY_TOOLS,
    taskAffinity: ["architecture-review", "backend-coding", "test-writing"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Review in findings-first order. Ground every concern in files, behavior, or tests. Mention residual risks when no blocking issue remains.",
  },
  {
    name: "ddd-validator",
    displayName: "DDD Validator",
    role: "DDD and Clean Architecture validator",
    description: "Checks bounded contexts, dependency direction, and domain leakage.",
    goal: "Keep domain boundaries explicit and enforceable.",
    tier: "fast",
    tools: READ_ONLY_TOOLS,
    taskAffinity: ["architecture-review", "backend-coding"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Look for layer violations, misplaced domain behavior, infrastructure leaks, and ambiguous bounded-context ownership.",
  },
  {
    name: "researcher",
    displayName: "Researcher",
    role: "Evidence researcher",
    description: "Gathers verified external or repository evidence before decisions.",
    goal: "Separate sourced facts from inference.",
    tier: "reasoning",
    tools: READ_ONLY_TOOLS,
    taskAffinity: ["research"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Use primary sources when external research is required. Clearly separate cited facts, local evidence, and inference.",
  },
  {
    name: "refactoring-specialist",
    displayName: "Refactoring Specialist",
    role: "Refactoring specialist",
    description: "Removes avoidable complexity while preserving behavior.",
    goal: "Improve structure without changing semantics.",
    tier: "reasoning",
    tools: WRITE_TOOLS,
    taskAffinity: ["mechanical-edit", "backend-coding"],
    mode: "managed-child",
    scope: "builtin",
    instructions: "Refactor only with behavior-preserving intent. Keep changes small, prove preservation with tests or compile checks, and avoid new abstractions without clear payoff.",
  },
] as const;
