export type {
  GuiProviderDescriptor,
  GuiSessionSummary,
  GuiSessionListResponse,
  GuiTelemetrySnapshot,
  GuiResumeInfo,
  GuiProviderThreadMeta,
  GuiDashboardSnapshot,
  GuiSessionMeta,
  GuiSessionTranscriptLine,
  GuiSessionDetail,
  GuiOutboundFrame,
  GuiInboundFrame,
  GuiSessionConnectionState,
} from "./frames.js";
