import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadAgentDefinitions } from "../application/agent-loader.js";
import { readKilnYaml } from "../kiln-yaml.js";

export interface AgentsMdSyncResult {
  written: boolean;
  path: string;
  errors: string[];
}

export async function syncAgentsMd(projectPath: string): Promise<AgentsMdSyncResult> {
  const targetPath = join(projectPath, "AGENTS.md");

  try {
    const agents = await loadAgentDefinitions(projectPath);
    const kilnYaml = readKilnYaml(join(projectPath, ".kiln"));

    const domain = kilnYaml?.domain ?? "default";
    const provider = kilnYaml?.provider ?? "claude";
    const model = kilnYaml?.model?.default ?? "provider default";
    const maxDepth = String(kilnYaml?.maxDepth ?? 3);
    const parallelWorkers = String(kilnYaml?.parallelWorkers ?? 1);

    const rows = [...agents]
      .sort((left, right) => left.name.localeCompare(right.name))
      .map((agent) => {
        const tools = agent.tools && agent.tools.length > 0 ? agent.tools.join(", ") : "-";
        const skills = agent.skills && agent.skills.length > 0 ? agent.skills.join(", ") : "-";
        return `| ${agent.name} (${agent.scope}) | ${agent.role} | ${tools} | ${agent.model ?? "-"} | ${skills} |`;
      });

    const lines: string[] = [
      "# Agents",
      "",
      "> Generated by kiln sync --agents-md. Do not edit manually.",
      "",
    ];

    if (kilnYaml) {
      lines.push(
        "## Team Configuration",
        "",
        "| Setting | Value |",
        "|---------|-------|",
        `| Domain | ${domain} |`,
        `| Default Provider | ${provider} |`,
        `| Default Model | ${model} |`,
        `| Max Depth | ${maxDepth} |`,
        `| Parallel Workers | ${parallelWorkers} |`,
        "",
      );
    }

    lines.push(
      "## Agents",
      "",
      "| Name | Role | Tools | Model | Skills |",
      "|------|------|-------|-------|--------|",
      ...rows,
      "",
    );

    if (rows.length === 0) {
      lines.push("No agent profiles defined. Create .kiln/agents/<name>.md to add one.", "");
    }

    lines.push(
      "## Usage",
      "",
      "Use `kiln run --agent <name>` to select an agent profile.",
      "Agent definitions live in `.kiln/agents/*.md` (project) or `~/.kiln/agents/*.md` (global).",
      "",
    );

    writeFileSync(targetPath, `${lines.join("\n")}`, "utf-8");

    return { written: true, path: targetPath, errors: [] };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { written: false, path: targetPath, errors: [message] };
  }
}
